### ISSUE TITLE
Add support for more file editor panes

### ISSUE THREAD

**Issue by HeroicEric** [ember-cli/ember-twiddle#122]
One thing that keeps me preferring JSBin right now is that it's hard to get the full context of what's going on by jumping around between files in ember twiddle. I think this can be improved a lot if we could add support for more file editor panes.

I think something that allows you to add/remove columns and horizontally split a column to show files above/below each other within a column would go a long way.

I'd like to try implementing this using [flexbox](https://philipwalton.github.io/solved-by-flexbox/demos/grids/) unless anybody has objections. [Browser support for flexbox](http://caniuse.com/#search=flexbox)

Looking for feedback

**Comment by Gaurav0** [comment]
@joostdevries has specific ideas about the user interface, so I'll defer to him, but my feeling is that users should be allowed to do this if they have screen space, but if they follow a link that opens 6 files and they are on a small screen or mobile they may have some difficulty. Not sure what the solution is to that specific issue.

**Comment by joostdevries** [comment]
I think a toggle with the # of editor cols (eg. 1-5) + a toggle whether or not to display output would pretty much do the trick. A horizontal split would clutter the UI I think (because of the controls you need for every editor).

For mobile, I'd say we'd some way to elegantly handle any possible amount of panes. Maybe hor. scroll or something..

**Comment by HeroicEric** [comment]
Closing since this has been implemented by https://github.com/ember-cli/ember-twiddle/pull/141 and more
