### ISSUE TITLE
Make header responsive

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#236]
Menus are unusable in mobile

**Comment by brianally** [comment]
I'm looking at that now. Because `.twiddle-panes` is positioned absolute we can't have the menu push down the content when it toggles open at mobile sizes. The menu will need a bg, and possible some layout, applied as it'll have to open above the content. But the absolute positioning also looks unnecessary. I'll follow that up tomorrow.

**Comment by Gaurav0** [comment]
Fixed by #293
