### ISSUE TITLE
Deleting files does not persist to previously saved gist.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-twiddle#237]
Deleting files does not persist to an already saved gist.

Steps:

1. Visit http://ember-twiddle.com/
2. Save (no changes needed)
3. Delete `application/controller.js` file
4. Save again.
5. Review gist.github.com (or reload the twiddle)

After step 5. the actual saved gist still contains deleted files.

**Comment by piotrpalek** [comment]
@rwjblue  I was looking at this and I noticed two weird things.

Steps to reproduce first weirdness:

1. Visit http://ember-twiddle.com/
2. Save (no changes needed)
3. Open ember inspector, open data tab, click the `$E` button for the `application/controller.js` gist-file model.
4. Delete application/controller.js file (normally like in the steps you provided)
5. Save again.
6. Review gist.github.com (or reload the twiddle) - now it works!

The issue here is that [this observer](https://github.com/ember-cli/ember-twiddle/blob/master/app/models/gist-file.js#L37) doesn't fire when the record wasn't send to the console(?).

So as an attempted workaround/fix I wanted to move this code into the `adapters/gist-file.js#deleteRecord` method. I didn't really dig into ember data / writing adapters before. But shouldn't that method fire when I call `gistFile.deleteRecord()`? (it doesn't)

**Comment by piotrpalek** [comment]
I created a [PR](https://github.com/ember-cli/ember-twiddle/issues/301) to fix this. I think the github adapters/serializers/models might be in need of a little review/refactor (deleting of gist-files is handled in the model by manually bookkeeping the deleted gist files, maybe this could be done cleaner in the adapters somehow, but then again it works for now.. :)). Anyway this at least fixes the bug for now.
