### ISSUE TITLE
navigation in tree appears to triggers reload

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-twiddle#290]
noticed it here: https://ember-twiddle.com/6a0c17f23fd8ce8ca95c?numColumns=1&route=%2Flocal-only

**Comment by piotrpalek** [comment]
Hey I've made a PR to fix this issue, any comments on this are welcomed.

Btw. another approach I could think of (if we don't want to depend on the CodeMirror event) is to add a `fileContent` property to the `file-editor-column` component, pass that property to CodeMirror (instead of `file.content`) and then set `fileContent` to `file.content` on the `valueUpdated` event. This would allow us to know if the change came from within CodeMirrir (`fileContent` would  be different from `file.content`) or was set on the component externally.

Thoughts?

**Comment by stefanpenner** [comment]
thanks, that PR looks good but likely needs a test. It should allow ember-twiddle to nicely address this issue. Good catch!

**Comment by piotrpalek** [comment]
I was thinking of adding a test but I was wondering what I should test there. Would checking if I'm passing 3 arguments suffice? I would want to stay away from testing that for eg. the "instance" argument has some sort of properties since that should be covered in CodeMirror itself.

**Comment by stefanpenner** [comment]
@piotrpalek ya, jsut a quick test ensuring all 3 args are passed should suffice.

**Comment by Gaurav0** [comment]
Fixed by #297

**Comment by stefanpenner** [comment]
:+1:
