### ISSUE TITLE
Can we make it look more like an editor than JSBin?

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-twiddle#328]
I'd love to be able to see all of the files as soon as the gist opens. At the moment, we have 2 split screen, instead I'd prefer to see the files and 1 open file. 

<img width="1274" alt="screen shot 2016-02-17 at 4 31 54 pm" src="https://cloud.githubusercontent.com/assets/74687/13125543/17dfc9f2-d594-11e5-81df-0897beef57d3.png">

Can I haz dis?

**Comment by alexspeller** [comment]
I actually think this is a better way to start with the files open, including all parts of the tree expanded - it's much easier to get a quick overview of what's in the twiddle that way. Slightly related, I'd personally like to be able to have a grid layout like jsfiddle instead of a column layout, as numerous small files are very common so it's be nice to see more at once.

**Comment by taras** [comment]
We could probably break this up into several changes. Start with this and later add ability to open files in split screen mode. Something like: "Double click to split screen, single click to replace currently open"

**Comment by Gaurav0** [comment]
Actually I was thinking if I should just make https://ember-twiddle.com?numFiles=1&fileTreeShown=true give @taras the effect he wanted.

**Comment by Gaurav0** [comment]
@taras Is bookmarking the link above enough; can I close this issue?

**Comment by taras** [comment]
I just checked. I'd prefer for that view to be default. Do you want me to get a vote going to see how many people would prefer to see the file list by defaut?

**Comment by Gaurav0** [comment]
@taras Feel free.

**Comment by taras** [comment]
Thank you @Gaurav0  :)
