### ISSUE TITLE
Switch to regular structure as default (not pods)

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#355]
Perhaps pods as option?

@wycats suggested.

**Comment by sheriffderek** [comment]
I think it would be better for on-boarding. It certainly confused me at first.

**Comment by wycats** [comment]
@Gaurav0 thanks for opening this!

@chancancode and I always use Twiddle and the other day we couldn't figure out how to make a partial, because of the non-standard structure (is it even possible?).

I would love for Ember Twiddle to feel like a first-class part of the Ember experience, aligned with the defaults in Ember CLI. An option for experimental features like pods seems great too. I'd love to be able to try out the new pods structure in Ember Twiddle once it solidifies.

**Comment by Gaurav0** [comment]
@wycats The non standard structure is just a default. Placing items in standard structure works, just as it does in ember-cli.

Partials do not work, but that has nothing to do with the structure.

**Comment by Gaurav0** [comment]
@wycats Sorry, I am incorrect. Partials do work in a pod structure. It's just that the pod structure for partials is different than I thought. See https://ember-twiddle.com/?openFiles=application.-stuff.hbs%2C
