### ISSUE TITLE
unable to demonstrate issue with renderTemplate

### ISSUE THREAD

**Issue by efx** [ember-cli/ember-twiddle#489]
I am trying to isolate a problem between ember ~2.6 and 2.7.3, but am unable to create an ember-twiddle demonstrating the exact issue. Basically, I override `renderTemplate` in my route hook.
Here is the saved twiddle that demonstrates the problem: https://ember-twiddle.com/1b250afd6ef1b71b4ef37c16841559d1

I expect to see the right hand side of the ember twiddle page show my rendered application.hbs template.

**Comment by Gaurav0** [comment]
Is this what you are trying to achieve? https://ember-twiddle.com/cc0f08cdc5ed281cb4b1fc9e2b47849e?openFiles=routes.index.js%2C

In http://emberjs.com/api/classes/Ember.Route.html#method_render, it does state you can only render into the _parents_ of the current route. However, it is a bug in Ember that it throws the error "TypeError: Cannot read outlets of null" rather than a more useful error message.

**Comment by efx** [comment]
ha, that makes much more sense @Gaurav0. Thanks for the fix.
