### ISSUE TITLE
Upgrade Twiddle to support latest versions of Ember

### ISSUE THREAD

**Issue by acorncom** [ember-cli/ember-twiddle#609]
As of today, Ember 2.16 is the latest version of Ember that is currently supported (per @Gaurav0). This issue will be used to track what is needed to get the rest of the way up to 3.1/3.2. I'm also going to start closing other issues that request similar things

- [x] 2.17 / 2.18 - should work once https://github.com/ember-cli/ember-twiddle/pull/608 is merged
- [ ] 3.0+ ? - @Gaurav0 do you know what blockers we hit here? globals resolver? other things?

**Comment by Gaurav0** [comment]
@acorncom 2.17 and 2.18 require #608, but also must be supported in the backend (so that addons will work), although I don't expect this to be difficult.

Regarding 3.0, because builds are no longer being published to S3, CDNs, etc. we need to start building ember-source on the backend. This will be considerable work.

**Comment by Gaurav0** [comment]
v0.14.0 now supports 2.17 and 2.18
