### ISSUE TITLE
Does not include sub-dependency "validated-changeset" in build, which is imported through ember-auto-import

### ISSUE THREAD

**Issue by jelhan** [ember-cli/ember-twiddle#709]
I tried to use `ember-changeset` as an addon in latest Ember Twiddle. It has `validated-changeset` as an dependency: https://github.com/poteto/ember-changeset/blob/21d896d775f07fc50d1aa6c1933eb11242538942/package.json#L41 For some reason that dependency seems to be not included in the build:

```
Uncaught Error: Could not find module `validated-changeset` imported from `ember-changeset/index`
    at loader-9d2ccefb0dfd6784cc87f799ef2c9f44.js:10
    at a (loader-9d2ccefb0dfd6784cc87f799ef2c9f44.js:10)
    at s.findDeps (loader-9d2ccefb0dfd6784cc87f799ef2c9f44.js:22)
    at a (loader-9d2ccefb0dfd6784cc87f799ef2c9f44.js:10)
    at s.findDeps (loader-9d2ccefb0dfd6784cc87f799ef2c9f44.js:22)
    at a (loader-9d2ccefb0dfd6784cc87f799ef2c9f44.js:10)
    at requireModule (loader-9d2ccefb0dfd6784cc87f799ef2c9f44.js:4)
    at Class._extractDefaultExport (twiddle-deps-92802e0eb833f951fd598b128254e31f.js:66)
    at Class.resolveOther (twiddle-deps-92802e0eb833f951fd598b128254e31f.js:30)
    at Class.resolve (twiddle-deps-92802e0eb833f951fd598b128254e31f.js:40)
```

You could reproduce with this Twiddle: https://ember-twiddle.com/01db3b47199b70d64fdbff3013cc696b/77156d01e3e2a6fdaa343f3aa4af7f7d717a2900?openFiles=twiddle%5C.json%2Ctemplates.components.my-component%5C.hbs

I tried to add `"validated-changeset": "0.2.2"` explicitly as an addon but faced a 404:

```
GET https://howq105a2c.execute-api.us-east-1.amazonaws.com/production/addon?ember_version=3.14.3&addon=validated-changeset&addon_version=0.2.2 404 (Not Found)
```

`validated-changeset` is not an ember addon but a normal NPM package. It uses `ember-auto-import` to import it. I tried to add `ember-auto-import` explicitly as a dependency but it throws a build error:

```
Addon ember-auto-import encountered a build error:
- Installing addon package

- Installing addon package
Installing packages... This might take a couple of minutes.
- Installing addon package
- npm: Installing ember-auto-import@1.5.3 ...
npm: Installed ember-auto-import@1.5.3
Installed addon package.
- Building
Environment: development
- Building
- building... 
- cleaning up
cleaning up...
- cleaning up
Build Error (SourceMapConcat)

Concat: nothing matched [**/*.js]


Stack Trace and Error Report: /tmp/error.dump.778853e70a5029d4222fa849517bb0e1.log

No addon.js created
```

Is `ember-auto-import` not supported by Ember Twiddle (yet)?

**Comment by Gaurav0** [comment]
I don't really "support" addons, I make a best effort to do what ember-cli does. I actually use ember-cli itself to build the addon. So try this:

1. Clone and download https://github.com/joostdevries/twiddle-backend
2. Run the following on the command line: `./script/test-ember-version-locally 3.14.0 ember-changeset 3.0.6`
3. look in `/tmp/3.14.0/dist/addon*.js`

You will see there are references to "validatedChangeset" but that it is never defined.

Clearly, it should be there if `ember-auto-import` imported it via `app.import` or returned it from one of the following hooks: `treefor` or `package`. But it isn't. There were no errors on build.

So what happened?

ember-cli (and twiddle backend is using ember-cli) looks in `node_modules/ember-auto-import/package.json` for the `main` file. That file is specified to be `js/index.js`.

If you look in `tmp/3.14.0/node_modules/ember-auto-import` there is indeed a `js/index.js`. It includes two hooks implemented (`setupProcessorRegistry` and `included` (it actually includes 3, but since we aren't running fastboot, the third one never gets called)). ember-cli calls both these hooks. Neither of the hooks in `js/index.js` ever calls `app.import`. There is no `treefor` hook or a `package` hook in `js/index.js`. Quite frankly, I have no idea how the `ember-auto-import` addon ever inserts code into the broccoli build pipeline! My guess is there is some undocumented hook or build step I am not running, and that ember-cli does not run for me by default.

By the way, earlier versions of ember-auto-import used to work, so I don't know what changed.

@ef4 may, should he choose to do so, enlighten me. @rwjblue might have a clue as well.

In the meantime I have two suggestions:

1. Try including 'validated-changeset' from a CDN in the dependencies hash of twiddle.json. It would have to be already transpiled to amd format wherever it is on the Internet.

2. If 1validated-changeset` is in es6 format, just copy and paste it into a file in your twiddle. If you named it `validated-changeset.js` you would be able to import if from `twiddle/validated-changeset`.

I'm not sure either will work, but may be worth a try.

**Comment by Gaurav0** [comment]
Update:

Turns out ember-auto-import monkey patches addonPostprocessTree to append to assets/vendor.js using its own custom broccoli build.

Anyway, fixed in canary:
https://canary.ember-twiddle.com/25b51467eb5fe8fa743c523eefbb9cee?openFiles=twiddle%5C.json%2C

**Comment by jelhan** [comment]
Awesome. Thanks a lot!
